### ISSUE TITLE
atom 上传报错

### ISSUE THREAD

**Issue by hi-asan** [airclear/oss-uploader#2]
![image](https://user-images.githubusercontent.com/12293038/58553034-6a0bf180-8246-11e9-8cf5-7d889b0f2b9f.png)
直接复制文件进来没反应，但是截图后粘贴进来是能够触发动作，但是报这个错。。。

**Comment by airclear** [comment]
> ![image](https://user-images.githubusercontent.com/12293038/58553034-6a0bf180-8246-11e9-8cf5-7d889b0f2b9f.png)
> 直接复制文件进来没反应，但是截图后粘贴进来是能够触发动作，但是报这个错。。。

这个错误是插件markdown-assistant造成的，可以使用 https://atom.io/packages/markdown-assistant-sef 替代

**Comment by hi-asan** [comment]
OK。谢谢
